### ISSUE TITLE
portal-app . not able to run any of THREE commands successfully

### ISSUE THREAD

**Issue by gubbas** [Greensona/greensona#1]
**Project folder locally**
Sudhakars-MacBook-Pro:portal-app sudhakargubba$ pwd
/Users/sudhakargubba/workspace/projects/greensona/greensona/portal-app

**Run command : mvn clean spring-boot:run** 
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Run command : mvn clean install**
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Run command : mvn docker:build**
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource

Appears my JAVA is not correct

I am Using Java Version
java version "9.0.1"

**Comment by ayalamanchili** [comment]
closing this as java 8 fixed this
