### ISSUE TITLE
portal-web command not successful

### ISSUE THREAD

**Issue by gubbas** [Greensona/greensona#2]
**Workling dir**
/Users/sudhakargubba/workspace/projects/greensona/greensona/portal-web

**Run commands L ng serve** 

Could not find module "@angular-devkit/build-angular" from "/Users/sudhakargubba/workspace/projects/greensona/greensona/portal-web".

**Comment by ayalamanchili** [comment]
i think we can close this as your are able to run "npm install" and ng serve to runt huis

**Comment by gubbas** [comment]
This was fixed when "npm install" command was run.  Updated README appropriately. Closing

**Comment by gubbas** [comment]
It is resolved
